# Author::    Eric Crane  (mailto:eric.crane@mac.com)
# Copyright:: Copyright (c) 2026 Eric Crane.  All rights reserved.
#
require 'bundler/gem_tasks'
require 'rake/testtask'

Rake::TestTask.new( :test ) do |t|
  ENV[ 'GLOO_ENV' ] = 'TEST'

  t.warning = false
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList[ 'test/**/*_test.rb' ]
end

task :default => :test
